### ISSUE TITLE
运行后，打开vnc成功登录了qq，但是对 /ping /status等无反应。

### ISSUE THREAD

**Issue by Uzibird** [codysk/bgmi-qbot#2]
没错，又是我。- -，之前重做了下系统bgmi可以用了。
        
这是docker-compose配置文件![image](https://user-images.githubusercontent.com/40909658/68488252-9f018300-027f-11ea-95aa-6c39ee774f97.png)
运行后 
![image](https://user-images.githubusercontent.com/40909658/68488307-b80a3400-027f-11ea-9c34-3227f079045e.png) 可以登陆QQ 也可以安装别的插件使用 但是无法对你 /ping /status等命令做反应。  - -是不是应该再开一个端口？

**Comment by codysk** [comment]
- CQHTTP_WS_REVERSE_URL=ws://bgmi-qbot:8080/ws/
这个地址写bgmi-qbot 不要写127.0.0.1

**Comment by Uzibird** [comment]
成功了。 
 有修改更新频率的方法吗? 我bgmi响应日志里看 它是半个小时访问一次，能改成十分钟吗？

**Comment by codysk** [comment]
刷新频率没有留配置项 回头可以加上
一般来说半个钟头一次的频率已经不低了

**Comment by Uzibird** [comment]
行吧，多谢大佬。咱们换个页面见。
