### ISSUE TITLE
机器人所在的群会对所有 / 命令回应

### ISSUE THREAD

**Issue by Uzibird** [codysk/bgmi-qbot#3]
没有set 设置订阅的群   也会对 / 做出回应，例如 /甩头  之类的表情，然后机器人就会自己回应命令不存在。希望可以只对主人QQ回应或者只对设置订阅的群内回应。
（加在了学校跳蚤市场里监视想买东西的关键字，结果被一个/甩头表情骗了出来。。。然后让同学们艾特了个爽。。。）

**Comment by codysk** [comment]
不知为嘛 看着特别想笑hhhhhh

**Comment by Uzibird** [comment]
那就笑吧。。。。反正脸都丢了。

**Comment by codysk** [comment]
dev 分支已经有这功能了 见最新的 #4 
等我找回测试Q号测过在合到master上

**Comment by Uzibird** [comment]
我停掉容器然后替换了msg_handler.py 这样可以吗? 
我新创了群，用别的Q发 /ping 机器人依然会回复pong。
需要额外的命令设置吗?

**Comment by codysk** [comment]
dev分支上还更新了readme 多了个可配置环境变量
配置一下就好了 默认还是回复所有人

**Comment by Uzibird** [comment]
![批注 2020-01-10 191225](https://user-images.githubusercontent.com/40909658/72149040-2c2a9a80-33dd-11ea-9b88-7e0380d977e5.png)

是这样吗?  我重新建立了容器，没给任何群订阅，但是依然会对非主人QQ做出回应。

**Comment by codysk** [comment]
看来 还是得修

**Comment by codysk** [comment]
用最新的 master 分支 按照这样设置就好

**Comment by Uzibird** [comment]
我直接将master 里的 msg_handler.py 文件替换后重建qbot容器依然不行，改never也不行。

![image](https://user-images.githubusercontent.com/40909658/72317598-c25c0a80-36d4-11ea-88ea-777e5aacbfc6.png)
这样的配置文件对吗?

**Comment by codysk** [comment]
重新建容器看看？ 测过是OK的 管理员账号不受限制

**Comment by Uzibird** [comment]
抱歉。。。我可能找不到Master最新分支。
7efd7dbb9b34edd669b902a7496 这个？还是362b13db5909113e92d28f4？    
只需要把msg_handler.py      utils.py两个文件替换就可以吧？  
这两个我都分别复制了代码然后重新建立的容器  依然不行。。。

**Comment by codysk** [comment]
最新的master 就在7efd7上 你重新pull一下就好了
还有就是确保你的容器被删除重建了

**Comment by Uzibird** [comment]
我用docker rm 只删掉了 Qbot的容器，也用docker ps -a确认过没有了。coolq的容器不用删吧?

我把文件全删除 只留下了 docker-compsoe.yml（如上配置）和 .coolq的文件夹，下载了7efd7dbb9b34edd669b902a749604c6abf791483.zip →解压→ up -d。

我创建了三个人的讨论组 我 机器人 工具人， 工具人无管理员  /ping依然响应。

（我还把工具人在别的群的管理员去掉了，依然不行）

是我的姿势不正确吗?

**Comment by codysk** [comment]
我这讲的管理员指的是 admin_qq 设置的Q号 这个用户发的消息机器人无论如何都会回

**Comment by Uzibird** [comment]
我不是用这个号测的，我用另外一个Q号测的。

**Comment by codysk** [comment]
将之前的镜像也要删掉 确保是用最新的代码build出了的
还有 都用github了 为什么不 git clone/pull 呢

**Comment by Uzibird** [comment]
国内的机器，git上的文件直接拖过去会很慢。  

我重pull镜像试试。

**Comment by codysk** [comment]
目前镜像还是本地构建的
回头我将镜像发布到dockerhub好了 应该就没那么多奇怪事了

**Comment by Uzibird** [comment]
好吧，我正迷惑呢。 我看了下镜像pull时间是今天呢。。。

**Comment by codysk** [comment]
所以重新构建镜像之后能行么

**Comment by Uzibird** [comment]
现在可以了！！
  你有更改dockerhub上的镜像吗?  
我刚才看镜像创建时间是今天上午呀，但是都不行。刚才又重新pull了几次镜像终于成功了，前几次容器一直提示Exited (1)
